language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - build-tools-26.0.2
    - android-26
    - extra-android-m2repository

script:
   - ./gradlew build connectedCheck