package com.viseator.chartit.data.style;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.viseator.chartit.data.style.ChartStyleEntity;
import com.viseator.chartit.data.style.ChartSetStyleEntity;
import com.viseator.chartit.data.chart.ChartDataEntity;

import com.viseator.chartit.data.style.ChartStyleEntityDao;
import com.viseator.chartit.data.style.ChartSetStyleEntityDao;
import com.viseator.chartit.data.chart.ChartDataEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chartStyleEntityDaoConfig;
    private final DaoConfig chartSetStyleEntityDaoConfig;
    private final DaoConfig chartDataEntityDaoConfig;

    private final ChartStyleEntityDao chartStyleEntityDao;
    private final ChartSetStyleEntityDao chartSetStyleEntityDao;
    private final ChartDataEntityDao chartDataEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chartStyleEntityDaoConfig = daoConfigMap.get(ChartStyleEntityDao.class).clone();
        chartStyleEntityDaoConfig.initIdentityScope(type);

        chartSetStyleEntityDaoConfig = daoConfigMap.get(ChartSetStyleEntityDao.class).clone();
        chartSetStyleEntityDaoConfig.initIdentityScope(type);

        chartDataEntityDaoConfig = daoConfigMap.get(ChartDataEntityDao.class).clone();
        chartDataEntityDaoConfig.initIdentityScope(type);

        chartStyleEntityDao = new ChartStyleEntityDao(chartStyleEntityDaoConfig, this);
        chartSetStyleEntityDao = new ChartSetStyleEntityDao(chartSetStyleEntityDaoConfig, this);
        chartDataEntityDao = new ChartDataEntityDao(chartDataEntityDaoConfig, this);

        registerDao(ChartStyleEntity.class, chartStyleEntityDao);
        registerDao(ChartSetStyleEntity.class, chartSetStyleEntityDao);
        registerDao(ChartDataEntity.class, chartDataEntityDao);
    }
    
    public void clear() {
        chartStyleEntityDaoConfig.clearIdentityScope();
        chartSetStyleEntityDaoConfig.clearIdentityScope();
        chartDataEntityDaoConfig.clearIdentityScope();
    }

    public ChartStyleEntityDao getChartStyleEntityDao() {
        return chartStyleEntityDao;
    }

    public ChartSetStyleEntityDao getChartSetStyleEntityDao() {
        return chartSetStyleEntityDao;
    }

    public ChartDataEntityDao getChartDataEntityDao() {
        return chartDataEntityDao;
    }

}
